In [26]:
import numpy as np

X = np.array([
    [2,1,0,0,0,0],
    [2,0,1,0,0,0],
    [1,0,0,1,0,0],
    [1,0,0,0,1,1]
])
y = np.array([0,0,0,1])

alpha = 1

separated = [[x for x, t in zip(X, y) if t == c] for c in np.unique(y)]
count_sample = X.shape[0]
class_log_prior_ = [np.log(len(i) / count_sample) for i in separated]
count = np.array([np.array(i).sum(axis=0) for i in separated]) + alpha
feature_log_prob_ = np.log(count / count.sum(axis=1)[np.newaxis].T)

predict_log_proba = [(feature_log_prob_ * x).sum(axis=1) + class_log_prior_ for x in X]
#predict =  np.argmax(predict_log_proba, axis=1)
#print(predict)

[[6 2 2 2 1 1]
 [2 1 1 1 2 2]] [[ 0.42857143  0.14285714  0.14285714  0.14285714  0.07142857  0.07142857]
 [ 0.22222222  0.11111111  0.11111111  0.11111111  0.22222222  0.22222222]]
